var asdas = {
  "result": "SUCCESS",
  "message": "성공",
  "data": {
    "act_list": [
      {
        "num": 3,
        "act_no": "240402162807PJZA",
        "partner_cd": "SM00001",
        "partner_nm": "심패스",
        "carrier_type": "PR",
        "carrier_type_nm": "선불",
        "cust_type": "ME",
        "cust_type_nm": "일반",
        "usim_act_cd": "N",
        "usim_act_cd_nm": "신규가입",
        "name": "WWEQE",
        "phone_number": "번호없음",
        "usim_plan_nm": "EGM 선불 300M",
        "carrier_cd": "KT",
        "carrier_cd_nm": "KT",
        "mvno_cd": null,
        "usim_act_status": "A",
        "usim_act_status_nm": "접수중",
        "apply_date": "2024-04-02 오후 04:28",
        "act_date": null,
        "sign_yn": "N",
        "sign_yn_nm": "서명없음",
        "apply_forms": "Y",
        "attach_files": "N",
        "chk_eq_yn": null
      },
      {
        "num": 4,
        "act_no": "2404021433373IHN",
        "partner_cd": "SM00001",
        "partner_nm": "심패스",
        "carrier_type": "PR",
        "carrier_type_nm": "선불",
        "cust_type": "ME",
        "cust_type_nm": "일반",
        "usim_act_cd": "N",
        "usim_act_cd_nm": "신규가입",
        "name": "SKEKEKSKWKE",
        "phone_number": "번호없음",
        "usim_plan_nm": "EGM 선불 300M",
        "carrier_cd": "KT",
        "carrier_cd_nm": "KT",
        "mvno_cd": null,
        "usim_act_status": "A",
        "usim_act_status_nm": "접수중",
        "apply_date": "2024-04-02 오후 02:33",
        "act_date": null,
        "sign_yn": "N",
        "sign_yn_nm": "서명없음",
        "apply_forms": "Y",
        "attach_files": "N",
        "chk_eq_yn": null
      }
    ],
    "lastPage": 83,
    "totalNum": 165,
    "usim_act_status_code": [
      {"cd": "A", "value": "접수중"},
      {"cd": "B", "value": "접수완료"},
      {"cd": "P", "value": "개통진행중"},
      {"cd": "Y", "value": "개통완료"},
      {"cd": "D", "value": "접수취소"},
      {"cd": "W", "value": "개통보류"},
      {"cd": "C", "value": "개통취소"}
    ],
    "rowLimit": 2,
    "currentPage": 2
  }
};
