List carriers = [
  {"cd": "SK", "value": "SKT"},
  {"cd": "KT", "value": "KT"},
  {"cd": "LG", "value": "LG U+"}
];

List mvnos = [
  {"cd": "HPM", "value": "한패스 모바일"},
  {"cd": "COM", "value": "코드 모바일"},
  {"cd": "HVS", "value": "LG 헬로비젼"},
  {"cd": "UPM", "value": "U+ 유모바일"},
  {"cd": "KTM", "value": "KT M모바일"},
  {"cd": "KTS", "value": "KT Sky Life"},
  {"cd": "SVM", "value": "SK 7모바일"}
];

Map<String, dynamic> plansInfo = {
  "carrier_type": [
    {"cd": "PR", "value": "선불"},
    {"cd": "PO", "value": "후불"},
    {"cd": "RT", "value": "랜탈"}
  ],
  "mvno_cd": [
    {"cd": "HPM", "value": "한패스 모바일"},
    {"cd": "COM", "value": "코드 모바일"},
    {"cd": "HVS", "value": "LG 헬로비젼 "},
    {"cd": "UPM", "value": "U+ 유모바일"},
    {"cd": "KTM", "value": "KT M모바일"},
    {"cd": "KTS", "value": "KT Sky Life"},
    {"cd": "SVM", "value": "SK 7모바일"}
  ],
  "carrier_plan_type": [
    {"cd": "P", "value": "일반"},
    {"cd": "J", "value": "청소년"},
    {"cd": "S", "value": "시니어"}
  ],
  "lastPage": 16,
  "status_cd": [
    {"cd": "Y", "value": "사용중"},
    {"cd": "N", "value": "미사용"}
  ],
  "totalNum": 159,
  "agent_cd": [
    {"cd": "SP", "value": "심패스"},
    {"cd": "FS", "value": "퍼스트상사"},
    {"cd": "SJ", "value": "에스제이"}
  ],
  "carrier_cd": [
    {"cd": "SK", "value": "SKT"},
    {"cd": "KT", "value": "KT"},
    {"cd": "LG", "value": "LG U+"}
  ],
  "plan_list": [
    {
      "num": 1,
      "id": 236,
      "usim_plan_nm": "슬림유심500MB50분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 6490,
      "sales_fee": 4070,
      "discount_fee": 2420,
      "voice": "50분",
      "message": "50건",
      "cell_data": "500MB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 2,
      "id": 235,
      "usim_plan_nm": "슬림유심1GB50분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 10890,
      "sales_fee": 4950,
      "discount_fee": 5940,
      "voice": "50분",
      "message": "0건",
      "cell_data": "1GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 3,
      "id": 234,
      "usim_plan_nm": "슬림유심1GB100분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 11000,
      "sales_fee": 5170,
      "discount_fee": 5830,
      "voice": "100분",
      "message": "50건",
      "cell_data": "1GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 4,
      "id": 233,
      "usim_plan_nm": "슬림유심2GB200분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 20130,
      "sales_fee": 6600,
      "discount_fee": 13530,
      "voice": "200분",
      "message": "150건",
      "cell_data": "2GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 5,
      "id": 232,
      "usim_plan_nm": "The착한데이터유심1.3GB",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 19690,
      "sales_fee": 7900,
      "discount_fee": 11790,
      "voice": "무제한",
      "message": "무제한",
      "cell_data": "1.3GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 6,
      "id": 231,
      "usim_plan_nm": "The착한데이터유심2.5GB",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 22660,
      "sales_fee": 9900,
      "discount_fee": 12760,
      "voice": "무제한",
      "message": "무제한",
      "cell_data": "2.5GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 7,
      "id": 230,
      "usim_plan_nm": "The착한데이터유심3.6GB",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 25740,
      "sales_fee": 10800,
      "discount_fee": 14940,
      "voice": "무제한",
      "message": "무제한",
      "cell_data": "3.6GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 8,
      "id": 229,
      "usim_plan_nm": "The착한데이터유심300MB",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 16390,
      "sales_fee": 11550,
      "discount_fee": 4840,
      "voice": "무제한",
      "message": "무제한",
      "cell_data": "300MB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 9,
      "id": 228,
      "usim_plan_nm": "The착한데이터유심9GB3000분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 37400,
      "sales_fee": 17000,
      "discount_fee": 20400,
      "voice": "3,000분",
      "message": "무제한",
      "cell_data": "9GB",
      "video_etc": "",
      "qos": "-",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    },
    {
      "num": 10,
      "id": 227,
      "usim_plan_nm": "슬림안심유심1GB100분",
      "carrier_cd": "LG",
      "carrier_nm": "LG U+",
      "mvno_cd": "HVS",
      "mvno_nm": "LG 헬로비젼",
      "agent_cd": "SP",
      "agent_nm": "심패스",
      "basic_fee": 19800,
      "sales_fee": 8800,
      "discount_fee": 11000,
      "voice": "100분",
      "message": "50건",
      "cell_data": "1GB",
      "video_etc": "",
      "qos": "400Kbps",
      "carrier_plan_type": "P",
      "carrier_plan_type_nm": "일반",
      "carrier_type": "PO",
      "carrier_type_nm": "후불",
      "usim_fee": 0,
      "plan_fee": 0,
      "from_date": "2024-03-19 10:20:17.0",
      "expire_date": "9999-12-31 23:59:59.0",
      "status": "Y",
      "status_nm": "사용중",
      "reg_by": 0,
      "reg_time": "2024-03-19 10:20:17.0",
      "update_by": 0,
      "update_time": "2024-03-19 10:20:17.0"
    }
  ],
  "rowLimit": 10,
  "currentPage": 1
};
